[package]
name = "joshuaclarkelua/promise"
description = "(FORK) Promise implementation for Roblox"
version = "4.0.12"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["lib", "default.project.json", "LICENSE"]

[dependencies]
